---
- hosts: 'tinaroo'
  become: no
  vars:
    nimrod_home: "{{ root_dir }}/opt/{{ nimrod_package }}"
  tasks:
    - name: generate modulefile
      template:
        src: nimrod-embedded.lua.j2
        dest: "{{ module_path }}/{{ nimrod_version }}.lua"
    - name: extract nimrod
      unarchive:
        src: "{{ nimrod_tarball }}"
        dest: "{{ root_dir }}/opt"
        creates: "{{ nimrod_home }}/bin/nimrod"
    - name: make agent directory
      file:
        path: "{{ nimrod_home }}/agents"
        state: directory
    - name: copy agent binary
      copy:
        src: "{{ agent_binary }}"
        dest: "{{ nimrod_home }}/agents/{{ agent_binary | basename }}"
        mode: 0755
    - name: copy nimrun
      copy:
        src: "{{ nimrun_binary }}"
        dest: "{{ root_dir }}/bin/nimrun"
        mode: 0755

