---
- hosts: 'localhost'
  become: no
  tasks:
    - name: download openjdk tarball
      get_url:
        url: https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz
        dest: "./openjdk-11.0.2_linux-x64_bin.tar.gz"
        checksum: sha256:99be79935354f5c0df1ad293620ea36d13f48ec3ea870c838f20c504c9668b57
      register: openjdk_tarball
    - name: download qpid tarball
      get_url:
        url: http://archive.apache.org/dist/qpid/broker-j/7.1.2/binaries/apache-qpid-broker-j-7.1.2-bin.tar.gz
        dest: "./apache-qpid-broker-j-7.1.2-bin.tar.gz"
        checksum: sha256:b1c5f6e6ee2fd1e93fb40210b6d45d114f439c8b3eda40e3c9149ee75ce50ee9
      register: qpid_tarball
    - name: download nimrod tarball
      get_url:
        url: "{{ nimrod_url }}"
        dest: "./{{ nimrod_package }}.tar"
        checksum: "sha256:{{ nimrod_sha256 }}"
      register: nimrod_tarball

- hosts: 'nimrod_hosts'
  become: no
  vars:
    bin_dir: "{{ root_dir }}/bin"
    java_home: "{{ root_dir }}/lib/jvm/jdk-11.0.2"
    qpid_home: "{{ root_dir }}/opt/qpid-broker/7.1.2"
    nimrod_home: "{{ root_dir }}/opt/{{ nimrod_package }}"
  tasks:
    - name: create folders
      file: path={{ item }} state=directory
      loop: ["{{ root_dir }}", "{{ bin_dir }}", "{{ java_home }}", "{{ qpid_home }}"]
    - name: extract openjdk tarball
      unarchive:
        src: "{{ hostvars.localhost.openjdk_tarball.dest }}"
        dest: "{{ java_home }}/../"
        remote_src: no
        creates: "{{ java_home }}/bin/java"
    - name: extract qpid tarball
      unarchive:
        src: "{{ hostvars.localhost.qpid_tarball.dest }}"
        dest: "{{ root_dir }}/opt"
        remote_src: no
        creates: "{{ qpid_home }}/bin/qpid-server"
    - name: extract nimrod tarball
      unarchive:
        src: "{{ hostvars.localhost.nimrod_tarball.dest }}"
        dest: "{{ root_dir }}/opt"
        remote_src: no
        creates: "{{ nimrod_home }}/bin/nimrod"
    - block:
        - name: create module path (lmod)
          file:
            path: "{{ module_path_lmod }}/{{ nimrun_module_name }}"
            state: directory
          register: module_dir
        - name: generate modulefile (lmod)
          template:
            src: nimrod-embedded.lua.j2
            dest: "{{ module_dir.path }}/{{ nimrod_version }}.lua"
        - name: generate nimexec
          template:
            src: nimexec.j2
            dest: "{{ bin_dir }}/nimexec"
            mode: 0755
          vars:
            module_path: "{{ module_path_lmod }}"
      when: module_path_lmod is defined
    - block:
        - name: create module path (modules)
          file:
            path: "{{ module_path_modules }}/{{ nimrun_module_name }}"
            state: directory
          register: module_dir
        - name: generate modulefile (modules)
          template:
            src: nimrod-embedded.j2
            dest: "{{ module_dir.path }}/{{ nimrod_version }}"
        - name: generate nimexec
          template:
            src: nimexec.j2
            dest: "{{ bin_dir }}/nimexec"
            mode: 0755
          vars:
            module_path: "{{ module_path_modules }}"
      when: module_path_modules is defined
