all:
  vars:
    nimrod_version: "0.8.6"
    nimrod_package: "nimrod-{{ nimrod_version }}"
    
    # Change these to where the binaries are
    nimrod_tarball: "/path/to/{{ nimrod_package }}.tar"
    nimrun_binary: "/path/to/nimrun"
    agent_binary: "/path/to/bbb/agent-x86_64-pc-linux-musl"

    # Just in case we lose the binaries
    nimrod_commit_hash: 470521e5914867d758c2abcdc3d3c5ca770397ed
    nimrod_agent_commit_hash: f1e8174eb4dcc3a5b51a14811d12287cbf02aff9
  hosts:
    tinaroo:
      root_dir: /gpfs1/sw7/RCC/NimrodG/embedded
      module_path: /sw7/Modules/RCC/local/embedded-nimrod
